server:
    port : 8001
mybatis:
    type-aliases-package : com.jiang.model
    mapper-locations : classpath:mybatis/mapper/**/*.xml
    configuration:
        cache-enabled: true

spring:
    application:
        name: microservicecloud-dept
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/cloudDB01
        username: root
        password: 123456
        type: com.alibaba.druid.pool.DruidDataSource
        druid:
            filters: stat, wall, log4j
            max-active: 20
            initial-size: 1
            min-idle: 1
            max-wait: 60000
            time-between-eviction-runs-millis: 60000
            min-evictable-idle-time-millis: 300000
            validation-query: select 'x'
            test-while-idle: true
            test-on-borrow: false
            test-on-return: false

            # 打开PSCache，并且指定每个连接上PSCache的大小
            pool-prepared-statements: true
            max-open-prepared-statements: 20
            # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
            connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
            # 合并多个DruidDataSource的监控数据
            use-global-data-source-stat: true
            # 配置DruidStatFilter
            web-stat-filter:
                enabled: true
                url-pattern: "/*"
                exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
            # 配置DruidStatViewServlet
            stat-view-servlet:
                url-pattern: "/druid/*"
                allow:
                deny:
                login-username: druid
                login-password: druid
                reset-enable: false
eureka:
    client: #客户端注册进eureka服务列表内
        service-url:
            defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
    instance:
        instance-id: microservicecloud-dept8001-hystrix
        prefer-ip-address: true

info:
    app.name: microservicecloud
    company.name: www.atguigu.com
    build.artifactId: $project.artifactId$
    build.version: $project.version$